### ISSUE TITLE
Session fingerprint changed

### ISSUE THREAD

**Issue by rdunk** [mplusmuseum/mplusmuseum-cms#1]
Users are being automatically logged out of the CMS regularly with an error that looks something like this:

`User 'username' - Error: Session fingerprint changed (IP address or useragent) (IP: 0.0.0.0)`

This only seems to be happening in the new staging environment, check the session logs in the CMS for more details.

See [this post](https://processwire.com/talk/topic/14717-getting-logged-out-constantly/?do=findComment&comment=145757) on the ProcessWire forums. I can try this suggested fix unless a better solution can be suggested.

**Comment by micahwalter** [comment]
It makes sense to me to not include a user's IP address since they will likely get a new IP frequently.. I can make that change to the config file if that's what we want to do. Just LMK.

**Comment by rdunk** [comment]
Yep, I hadn't seen this caveat in the wire/config.php file:

>  If using fingerprint with an AWS load balancer, you should use one of the options that uses the “client IP” rather than the “remote IP”, fingerprint only the useragent, or disable fingerprinting.

Happy for you to make whichever change necessary in the untracked site/config.php file to update this.

**Comment by micahwalter** [comment]
OK I've set `$config->sessionFingerprint = 8;` on both staging and production, so please test it out and let me now if you see an improvement.

**Comment by chrismplus** [comment]
This seems to be better now. I'll monitor this throughout the day.

**Comment by rdunk** [comment]
Also no longer seeing this issue, closing for now.
