### ISSUE TITLE
SSL everything.

### ISSUE THREAD

**Issue by micahwalter** [mplusmuseum/mplusmuseum-cms#4]
Need some info on how SSL works with PW.

**Comment by rdunk** [comment]
My understanding is that just [these lines](https://github.com/mplusmuseum/mplusmuseum-cms/blob/7bf14c78c035389ca4e8b7ff1df7839dfcb5afc2/www/.htaccess#L97-L99) need to be uncommented. I'm not sure any other settings are required in the PW directory. Happy to push that change when needed.

**Comment by rdunk** [comment]
Attempted to force HTTPS in 5269ce9.

**Comment by micahwalter** [comment]
This is working
