### ISSUE TITLE
Set database to use utf8mb4

### ISSUE THREAD

**Issue by micahwalter** [mplusmuseum/mplusmuseum-cms#5]
For emoji support. 

1. RDS Parameter group setting.

**Comment by micahwalter** [comment]
http://aprogrammers.blogspot.com/2014/12/utf8mb4-character-set-in-amazon-rds.html?m=1

**Comment by micahwalter** [comment]
FYI @rdunk & @chrismplus this seems to be the default setting in RDS.

**Comment by chrismplus** [comment]
Can I get an update on this @rdunk, @micahwalter?

Unable to use emojis for tagging.

**Comment by micahwalter** [comment]
@chrismplus I am still doing some research on this one.

**Comment by micahwalter** [comment]
@chrismplus I think it should be all set. Please test this out.

**Comment by chrismplus** [comment]
@micahwalter Same result. The emoji tags reverts to a series of question marks in the CMS.

**Comment by micahwalter** [comment]
Looking at the tables, they seem to have the correct character encoding set.

```
mysql> SELECT CCSA.character_set_name FROM information_schema.`TABLES` T,information_schema.`COLLATION_CHARACTER_SET_APPLICABILITY` CCSA WHERE CCSA.collation_name = T.table_collation AND T.table_schema = "processwire" AND T.table_name = "pages";
+--------------------+
| character_set_name |
+--------------------+
| utf8mb4            |
+--------------------+
1 row in set (0.00 sec)
```

**Comment by chrismplus** [comment]
Is there a way we can compare all MySQL variables from the ZG Dev server with Production? If the issue's a rogue setting that might be able to uncover it...

**Comment by micahwalter** [comment]
I was able to fix this. I had to do several steps including adding this line to the config.php - 

`$config->dbCharset = 'utf8mb4';`

I know its working for `field_title` values, but not confident it will work in other places like body content. Please test throughout the CMS and let me know.

**Comment by micahwalter** [comment]
Looks like this is working now throughout the CMS.
